# Generated by Django 4.2.2 on 2023-06-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coffee_voting.brand'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='production_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coffee_voting.production'),
        ),
    ]
